### ISSUE TITLE
Can you share the pretrained model?

### ISSUE THREAD

**Issue by ran337287** [kentsyx/Neural-IMage-Assessment#3]
Hello,  your project is great， can you share the pretrained model?

**Comment by ran337287** [comment]
Thank you for your sharing！

**Comment by wangyu0303** [comment]
> Hi @ran337287 please refer to the link in README

The link is not exist now. Could you share the pretrained model with me?

**Comment by wangyu0303** [comment]
Could you share the pretrained model with me?
