### ISSUE TITLE
Doubt regarding computing standard deviation

### ISSUE THREAD

**Issue by asprasan** [kentsyx/Neural-IMage-Assessment#7]
In line 195-196 of the `main.py` file you are computing the standard deviation of the score. The for loop is over the variable `j` while the variable used inside the loop is `i`. I just wanted to clarify if this is correct. Thank you in advance.

**Comment by kentsyx** [comment]
Hi, 

Yes you are correct, it should be variable ```j``` instead of ```i```, might be a typo which I already fixed.
