### ISSUE TITLE
Creating the dataset partitions

### ISSUE THREAD

**Issue by prashanthvs** [kentsyx/Neural-IMage-Assessment#8]
Can you please share the CSV files that you used to generate the data partitions for train, val and test.

**Comment by kentsyx** [comment]
Hi, 

I don't seem to have the csv files locally anymore, but creating them is fairly easy, say the original info files look like this (after some simple preprcocessing)
```2 2 3 4 12 21 22 12 4 6
...
```
each number stands for the number of people voted for that score bucket, than you just divide them by their sum to form a empirical distribution,
```
0.02273 0.02273 0.03409 0.04545 0.13636 0.23863 0.13636 0.04545 0.06818
...
```
then you can go ahead to create your train/test split.

**Comment by KevinTech0916** [comment]
img_path
csv_file
how can I determine these, according to AVA.txt?
I am not very familiar with data processing. Need your help
Thank you ! your code is awesome !

**Comment by kentsyx** [comment]
It is now provided in README
