### ISSUE TITLE
How to run the pretrained model?

### ISSUE THREAD

**Issue by JennieLiu** [kentsyx/Neural-IMage-Assessment#9]

**Comment by JennieLiu** [comment]
I didn't find usage for the pretrained model

**Comment by JennieLiu** [comment]
I just want to get score for a single pic

**Comment by kentsyx** [comment]
First construct the model [like this](https://github.com/kentsyx/Neural-IMage-Assessment/blob/master/main.py#L41-L42), then [load the pretrained model](https://github.com/kentsyx/Neural-IMage-Assessment/blob/master/main.py#L45), and follow [here](https://github.com/kentsyx/Neural-IMage-Assessment/blob/master/main.py#L178-L198) to get a predicted score

**Comment by wangyu0303** [comment]
> I just want to get score for a single pic

Could you share the pretrained model with me?
